<a href="https://colab.research.google.com/github/kinghukang/gitby_platform/blob/master/assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Preprocessing

### Import the Libraries

In [2]:
import pandas as pd

### Load & Explore Business Datasets

**Q1.1** - Load each source CSV file into an individual Pandas dataframe for structured analysis. **(2 marks)**

**Hint** - For loading the customers file use **encoding** parameter

In [19]:
customer=pd.read_csv("/content/Customers.csv",encoding="latin1")
data= pd.read_csv("/content/Data_Dictionary.csv",encoding="latin1")
exchange=pd.read_csv("/content/Exchange_Rates.csv",encoding="latin1")
products = pd.read_csv("/content/Products.csv",encoding="latin1")
sales = pd.read_csv("/content/Sales.csv",encoding="latin1")
stores = pd.read_csv("/content/Stores.csv",encoding="latin1")

customer.head(10)

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965
5,1086,Male,Hayden Clegg,TEMPLERS,SA,South Australia,5371,Australia,Australia,1/20/1954
6,1133,Male,Nicholas Caffyn,JUBILEE POCKET,QLD,Queensland,4802,Australia,Australia,11/22/1969
7,1256,Male,Lincoln Jenks,KULLOGUM,QLD,Queensland,4660,Australia,Australia,3/12/1950
8,1314,Male,Isaac Israel,EDITH RIVER,NT,Northern Territory,852,Australia,Australia,12/21/1965
9,1568,Male,Luke Virtue,KOTTA,VIC,Victoria,3565,Australia,Australia,7/25/1975

### Check Data Dimensions

**Q1.2** - Display the shape of each dataframe. **(1 mark)**

In [20]:
customer.shape
products.shape
sales.shape
stores.shape
exchange.shape

(11215, 3)

### Check for the Data Types

**Q1.3** - Inspect the datatypes of all the columns in each dataset. **(1 mark)**

In [21]:
customer.dtypes
products.dtypes
sales.dtypes
stores.dtypes
exchange.dtypes

Date         object
Currency     object
Exchange    float64
dtype: object

### Identify Data Type Issues

**Q1.4** - Identify the potential data type issues. Give the names of the columns which have these issues. **(2 marks)**

In [22]:
customer.info()
products.info()
sales.info()
stores.info()
exchange.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15256 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  object
dtypes: int64(1), object(9)
memory usage: 1.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   object
 5   Unit Price USD  2517 non-null   object
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   object
dtypes: int64(3), object(7)
memory usage: 196.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  object
 3   Delivery Date  13165 non-null  object
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: int64(6), object(3)
memory usage: 4.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StoreKey       67 non-null     int64
 1   Country        67 non-null     object
 2   State          67 non-null     object
 3   Square Meters  66 non-null     float64
 4   Open Date      67 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11215 entries, 0 to 11214
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      11215 non-null  object
 1   Currency  11215 non-null  object
 2   Exchange  11215 non-null  float64
dtypes: float64(1), object(2)
memory usage: 263.0+ KB

#Write your observations as markdown text here
The following columns have data type issues: Birthday, Order Date, Delivery Date, Open Date, and Date columns are stored as object instead of datetime. Unit Cost USD and Unit Price USD are stored as object instead of numeric. Zip Code is stored as object and should be treated as categorical/string. These columns must be converted to appropriate data types for accurate analysis.

### Convert Date Columns

**Q1.5** - Convert all date-related columns to a standardised datetime format. **(2 marks)**
* **Hint** - Use datetime function

In [26]:
customer["Birthday"] = pd.to_datetime(customer["Birthday"])
sales["Order Date"] = pd.to_datetime(sales["Order Date"])
sales["Delivery Date"] = pd.to_datetime(sales["Delivery Date"])
stores["Open Date"] = pd.to_datetime(stores["Open Date"])
exchange["Date"] = pd.to_datetime(exchange["Date"])
customer

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,1939-07-03
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,1979-09-27
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,1947-05-26
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,1957-09-17
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,1965-11-19
...,...,...,...,...,...,...,...,...,...,...
15261,2099600,Female,Denisa Duková,Houston,TX,Texas,77017,United States,North America,1936-03-25
15262,2099618,Male,Justin Solórzano,Mclean,VA,Virginia,22101,United States,North America,1992-02-16
15263,2099758,Male,Svend Petrussen,Wilmington,NC,North Carolina,28405,United States,North America,1937-11-09
15264,2099862,Female,Lorenza Rush,Riverside,CA,California,92501,United States,North America,1937-10-12
15265,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,1965-08-18

### Transform Numerical Columns

**Q1.6** - Transform object-type columns containing numeric information into numerical data types for analysis. **(2 marks)**
* **Hint** - Use Replace function

In [29]:
customer["Zip Code"] = customer["Zip Code"].replace(r"[^0-9]", "", regex=True)
customer["Zip Code"] = pd.to_numeric(customer["Zip Code"], errors="coerce")
customer["Zip Code"] = customer["Zip Code"].astype("Int64")
products["Unit Cost USD"] = (
    products["Unit Cost USD"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype(float)
)

products["Unit Price USD"] = (
    products["Unit Price USD"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype(float)
)

customer

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,1939-07-03
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,1979-09-27
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,1947-05-26
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,1957-09-17
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,1965-11-19
...,...,...,...,...,...,...,...,...,...,...
15261,2099600,Female,Denisa Duková,Houston,TX,Texas,77017,United States,North America,1936-03-25
15262,2099618,Male,Justin Solórzano,Mclean,VA,Virginia,22101,United States,North America,1992-02-16
15263,2099758,Male,Svend Petrussen,Wilmington,NC,North Carolina,28405,United States,North America,1937-11-09
15264,2099862,Female,Lorenza Rush,Riverside,CA,California,92501,United States,North America,1937-10-12
15265,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,1965-08-18

### Rename Columns

* **Q1.7.1** - Change the column names from Country to Customer_country and from State to Customer_state in customers dataframe. **(1 mark)**
* **Q1.7.2** - Change the column names from Country to Stores_Country and from State to Stores_State in stores dataframe. **(1 mark)**

In [30]:
customer.rename(columns={"Country":"Customer_country",
                         "State":"Customer_state"}, inplace=True)

stores.rename(columns={"Country":"Stores_Country",
                       "State":"Stores_State"}, inplace=True)
customer

,CustomerKey,Gender,Name,City,State Code,Customer_state,Zip Code,Customer_country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,1939-07-03
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,1979-09-27
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,1947-05-26
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,1957-09-17
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,1965-11-19
...,...,...,...,...,...,...,...,...,...,...
15261,2099600,Female,Denisa Duková,Houston,TX,Texas,77017,United States,North America,1936-03-25
15262,2099618,Male,Justin Solórzano,Mclean,VA,Virginia,22101,United States,North America,1992-02-16
15263,2099758,Male,Svend Petrussen,Wilmington,NC,North Carolina,28405,United States,North America,1937-11-09
15264,2099862,Female,Lorenza Rush,Riverside,CA,California,92501,United States,North America,1937-10-12
15265,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,1965-08-18

### Handle Duplicates

**Q1.8** - Perform duplicate checks across all datasets to ensure uniqueness and prevent data inflation during aggregations. **(2 marks)**
* **Hint** - Use Duplicate function

In [31]:
customer.duplicated().sum()
products.duplicated().sum()
sales.duplicated().sum()
stores.duplicated().sum()
exchange.duplicated().sum()

np.int64(0)

### Handle Missing Values

**Q1.9** - Analyse and comment on the missing values present in each dataset. **(2+1=3 marks)**

In [32]:
customer.duplicated().sum()
products.duplicated().sum()
sales.duplicated().sum()
stores.duplicated().sum()
exchange.duplicated().sum()

np.int64(0)

#Write your comments as markdown text here

No duplicate records were found in the dataset. All rows are unique across the tables.

### Join the Tables

In [34]:
# Merge FX rates
sales_fx = sales.merge(
    exchange,
    left_on=['Order Date', 'Currency Code'],
    right_on=['Date', 'Currency'],
    how='left'
)

# Merge master data
sales_full = (
    sales_fx
    .merge(customer, on='CustomerKey', how='left')
    .merge(products, on='ProductKey', how='left')
    .merge(stores, on='StoreKey', how='left')
)

* A consolidated, analysis-ready dataset (sales_full) containing transactional, customer, product, store, and currency information in a single table.

### Normalise the Revenue

In [36]:
# Create USD-normalised revenue
sales_full['Revenue_USD'] = (
    sales_full['Quantity'] *
    sales_full['Unit Price USD'] *
    sales_full['Exchange']
)

* Revenue was converted to USD to enable consistent cross-country financial analysis.

## Exploratory Analysis

### Find Total Revenue

**Q2.1** - Calculate the total revenue in USD. **(1 mark)**

In [37]:
sales_full["Revenue_USD"].sum()

np.float64(55349466.101787)

### Find Revenue by Product Categories

**Q2.2** - How much total revenue (in USD) is generated by each product category? **(2 marks)**

In [51]:
sales=sales_full.groupby("Category")["Revenue_USD"].sum()
sales = sales.astype(int)
sales

Category
Audio                             3147476
Cameras and camcorders            6502487
Cell phones                       6118492
Computers                        19143319
Games and Toys                     718602
Home Appliances                  10747777
Music, Movies and Audio Books     3113971
TV and Video                      5857337
Name: Revenue_USD, dtype: int64

### Find Top 5 Best Performing Stores by Revenue

**Q2.3** - Which 5 stores generate the highest total revenue in USD?  Sort the values in descending order. **(3 marks)**

In [50]:
sales_full.groupby("StoreKey")["Revenue_USD"].head(5)

0          94.411200
1         854.000000
2         665.940000
3        3129.453600
4         452.618400
            ...
34064     534.624356
34065      15.825936
34066      37.132137
34067    1024.319450
34323     761.358000
Name: Revenue_USD, Length: 290, dtype: float64

### Find Top 5 Products by Quantity Sold

**Q2.4** - What are the top 5 products based on the number of units sold? **(2 marks)**

In [52]:
sales_full.groupby("Product Name")["Quantity"] \
          .sum() \
          .sort_values(ascending=False) \
          .head(5)

Product Name
WWI Desktop PC2.33 X2330 Black                550
WWI Desktop PC1.80 E1800 White                538
Adventure Works Desktop PC2.30 MD230 White    521
Adventure Works Desktop PC1.60 ED160 Black    521
Adventure Works Desktop PC1.80 ED180 Black    520
Name: Quantity, dtype: int64

## Business Questions

###	Find Store Revenue Efficiency Metric

* **Q3.1.1** - Which metric can be used to assess a store’s revenue-generating efficiency relative to its physical size (come up with a metric)? **(1 mark)**
* **Q3.1.2 and 3.1.3** - How can we calculate this metric for each store (write a Python code)?  **(3 marks)**
* **Q3.1.4** - What insights and recommendations can be derived from this metric?  **(2 marks)**

**Note** - Give atleast 1 insight and 1 recommendation

#Write your metric as markdown text here

In [ ]:
#Write your code here

#Write your insight and recommendation as markdown text here

###	Find Revenue Growth Metric

* **Q3.2.1** - Which metric can be used to measure the company’s revenue growth over month on month (come up with a metric)? **(1 mark)**
* **Q3.2.2 and 3.2.3** - How can we calculate this metric for each store (write a Python code)?  **(3 marks)**
* **Q3.2.4** - What insights and recommendations can be derived from this metric?  **(2 marks)**

**Note** - Give atleast 1 insight and 1 recommendation

#Write your metric as markdown text here

In [ ]:
#Write your code here

#Write your insight and recommendation as markdown text here

### Perform Store Age–Based Segmentation

* **Q3.3.1 and 3.3.2** - Calculate the age of the stores in 5 buckets ('0–5 years', '5–10 years', '10–15 years', '15–20 years', '20+ years'). **(3 marks)**
* **Q3.3.3** - Calculate the total revenue in each bucket (write a Python code). **(2 marks)**
* **Q3.3.4** - Calculate the average revenue per store in each bucket (write a Python code). **(2 marks)**
* **Q3.3.5** - What insights and recommendations can be derived from this metric? **(2 marks)**

**Note** - Give atleast 1 insight and 1 recommendation

In [ ]:
#Write your code here

In [ ]:
#Write your code here

In [ ]:
#Write your code here

#Write your insight and recommendation as markdown text here

## Prompting Related

Answer the following subjective questions. Each question carries 1 mark. Type your answer as markdown text after each question. **(4 marks)**

* **Q4.1** - If you had to use an LLM for measuring store revenue efficiency from the given datasets (Q.3), how would you frame your prompt? What key details would you include in your prompt?

#Write your answer as markdown text here

* **Q4.2** - Based on the tasks given in this assignment, give 1 example of a prompt you would use. State which type of prompt it represents: zero-shot, few-shot, and chain of thought.

#Write your answer as markdown text here

* **Q4.3** - Use an LLM of your choice to perform data preprocessing on the given datasets. What tasks did the LLM perform well? Where can it improve?

#Write your answer as markdown text here

* **Q4.4** - What type of prompting (zero shot, few shot, chain of thought) did you primarily use in the previous scenario (4.2)? Why?

#Write your answer as markdown text here